name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/240 * * * *"
  push:
    branches:
      - main
    paths-ignore: 
      - "**/README.md" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Prepare Workstation
        shell: bash
        run: |
          git config --global init.defaultBranch main
          
          wget `curl -s https://api.github.com/repos/zhanhb/cidr-merger/releases/latest | grep -Po '(?<=download_url\"\: \").*linux-amd64'`
          mv ./cidr-merger-linux-amd64 ./cidr-merger
          chmod +x ./cidr-merger
          
          mkdir -p ./publish

      - name: Get Upstream
        run: |
          curl -L https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt -o chnroutes.txt
          sed '/^\#/d' chnroutes.txt > ipv4-chnroutes.txt
          
          curl -L https://raw.githubusercontent.com/metowolf/iplist/master/data/special/china.txt -o ipv4-metowolf.txt
          curl -L https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt -o ipv4-china.txt
          curl -L https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt -o ipv4-china_ip_list.txt
          curl -L https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/googlecn.txt -o ipv4-googlecn.txt
          curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > ipv4-apnic.txt
          
          cat ./ipv4*.txt | ./cidr-merger -s > ./ipv4.txt
          
          curl -L https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt -o ipv6-china6.txt
          curl -L https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/googlecn6.txt -o ipv6-googlecn6.txt
          curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv6 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > ipv6-apnic.txt
          
          cat ./ipv6*.txt | ./cidr-merger -s > ./ipv6.txt
          
          curl -L https://raw.githubusercontent.com/v2fly/geoip/release/text/cn.txt -o maxmind-cn.txt
          
          cat ipv4.txt ipv6.txt maxmind-cn.txt | ./cidr-merger -s > publish/ip.txt
          
      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions@github.com"
          git checkout -b release
          git add --all
          git commit -m "sync"
          git remote add china-ip-list "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f china-ip-list release
